# Site Settings
title: Sakshi Vishnoi
title_separator: "-"
subtitle: Operations Research & Supply Chain
name: Sakshi Vishnoi
description: >-
  Portfolio showcasing work in logistics optimization, supply chain,
  and marketplace systems.
url: ""
baseurl: ""
repository: "vishsak09/vishsak09.github.io"

# Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Sakshi Vishnoi"
  avatar: # "/assets/images/bio-photo.jpg" # Add your photo here if you have one
  bio: "Operations Research & Supply Chain Engineer specializing in logistics optimization, marketplace systems, and ML-driven decision engines."
  location: "Bengaluru, India"
  email: "vishsak09@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/sakshivishnoi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vishsak09"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/sakshivishnoi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vishsak09"

# Reading Files
include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - .gitignore

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: false
      related: false

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
